### ISSUE TITLE
not update with the modified Estimator class

### ISSUE THREAD

**Issue by amiltonwong** [pqhieu/sota3d#1]
Hi, @pqhieu ,

I found that [main.py](https://github.com/pqhieu/sota3d/blob/master/sota3d/s3dis/main.py#L11) in s3dis did not update with the modified Estimator class. It just used previous Trainer class.

**Comment by pqhieu** [comment]
Hi @amiltonwong,

I'm still working on the S3DIS benchmark. All of the inconsistencies will be resolved with the first release.

**Comment by pqhieu** [comment]
Now updated with `torch3d` v0.2.0
